import type React from 'react';

// ── Group brand colors ──
export const GROUP_COLORS: Record<string, string> = {
  '乃木坂46': '#742581',
  '櫻坂46': '#F19DB5',
  '樱坂46': '#F19DB5',
  '日向坂46': '#7BC7E8',
};

export function getGroupColor(group: string): string {
  return GROUP_COLORS[group] || '#742581';
}

// ── Group display names ──
export const GROUP_CONFIG: Record<string, { name: string; key: string }> = {
  '乃木坂46': { name: '乃木坂', key: 'nogizaka' },
  '櫻坂46': { name: '櫻坂', key: 'sakurazaka' },
  '樱坂46': { name: '櫻坂', key: 'sakurazaka' },
  '日向坂46': { name: '日向坂', key: 'hinatazaka' },
};

// ── R2 avatar URL (msg-avatars = member thumbnails from /v2/members) ──
export const R2_AVATAR_BASE = 'https://media.46log.com/msg-avatars';
const AVATAR_VERSION = 'v2'; // bump to bust browser cache after re-upload

// 半角カタカナ→全角カタカナ (must match upload script normalization)
const HW = 'ｦｧｨｩｪｫｬｭｮｯｰｱｲｳｴｵｶｷｸｹｺｻｼｽｾｿﾀﾁﾂﾃﾄﾅﾆﾇﾈﾉﾊﾋﾌﾍﾎﾏﾐﾑﾒﾓﾔﾕﾖﾗﾘﾙﾚﾛﾜﾝﾞﾟ';
const FW = 'ヲァィゥェォャュョッーアイウエオカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワン゛゜';
function normalizeKana(s: string): string {
  let r = '';
  for (const c of s) { const i = HW.indexOf(c); r += i >= 0 ? FW[i] : c; }
  return r.replace(/([カキクケコサシスセソタチツテトハヒフヘホ])゛/g, (_, c) => {
    const d = 'ガギグゲゴザジズゼゾダヂヅデドバビブベボ';
    const b = 'カキクケコサシスセソタチツテトハヒフヘホ';
    return d[b.indexOf(c)] || c + '゛';
  }).replace(/([ハヒフヘホ])゜/g, (_, c) => {
    const h = 'パピプペポ'; const b = 'ハヒフヘホ';
    return h[b.indexOf(c)] || c + '゜';
  });
}

export function getR2AvatarUrl(name: string): string {
  return `${R2_AVATAR_BASE}/${normalizeKana(name).replace(/\s+/g, '_')}.jpg?${AVATAR_VERSION}`;
}

// ── Optimized avatar URL (direct R2 via custom domain, Cloudinary 国内不可用已移除) ──
export function getOptimizedAvatarUrl(name: string, size: number = 100): string {
  return getR2AvatarUrl(name);
}

// ── Group-specific MSG header styles ──
export function getHeaderStyle(group: string): React.CSSProperties {
  const base: React.CSSProperties = {
    textAlign: 'center' as const,
    fontSize: '20px',
    fontWeight: 300,
    letterSpacing: '0.5px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '16px 60px',
    borderRadius: '12px 12px 0 0',
    position: 'relative',
  };

  if (group === '日向坂46') {
    return { ...base, backgroundImage: 'linear-gradient(90deg, rgb(142, 196, 230) 40%, rgb(167, 123, 208))', color: '#fff' };
  }
  if (group === '樱坂46' || group === '櫻坂46') {
    return {
      ...base,
      backgroundColor: '#fff',
      backgroundImage: 'linear-gradient(90deg, #fff 0%, rgb(243, 144, 177) 40%, rgb(162, 84, 165) 100%)',
      backgroundPosition: '50% 100%',
      backgroundSize: '100% 2px',
      backgroundRepeat: 'no-repeat',
      color: '#F19DB5',
    };
  }
  // 乃木坂46
  return { ...base, backgroundImage: 'linear-gradient(90deg, rgb(196, 133, 230), rgb(147, 63, 185))', color: '#fff' };
}

// ── Generation sort ──
const GEN_ORDER: Record<string, number> = {
  '1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9, '10': 10,
  '一': 1, '二': 2, '三': 3, '四': 4, '五': 5, '六': 6, '七': 7, '八': 8, '九': 9, '十': 10,
};

export function genSortKey(gen: string): number {
  const m = gen.match(/^(\d+|[一二三四五六七八九十])/);
  return m ? (GEN_ORDER[m[1]] || 99) : 99;
}

export function sortedGenEntries<T>(byGen: Record<string, T[]>): [string, T[]][] {
  return Object.entries(byGen).sort((a, b) => genSortKey(a[0]) - genSortKey(b[0]));
}

// ── Member data types ──
export interface MemberInfo {
  name: string;
  group: string;
  generation?: string;
  imageUrl: string;
}

// ── Shared member data loader ──
// Fetches from R2 (msg-avatars/members.json) first, falls back to local /data/member-images.json
const R2_MEMBERS_URL = `${R2_AVATAR_BASE}/members.json`;

export async function fetchMemberData(): Promise<Record<string, any>> {
  // Try R2 first (generated by fetch-msg-avatars-standalone.js)
  try {
    const res = await fetch(R2_MEMBERS_URL);
    if (res.ok) {
      const data = await res.json();
      if (data.images && Object.keys(data.images).length > 0) {
        return data.images;
      }
    }
  } catch { /* fall through */ }

  // Fallback to local static file
  const res = await fetch('/data/member-images.json');
  const data = await res.json();
  return data.images || {};
}

// Deduplicate: keep spaced name when both spaced and unspaced versions exist
export function deduplicateMembers(images: Record<string, any>): Record<string, any> {
  const allNames = new Set(Object.keys(images));
  const result: Record<string, any> = {};
  for (const [name, info] of Object.entries(images)) {
    if (!name.includes(' ')) {
      let hasSpaced = false;
      for (const other of allNames) {
        if (other !== name && other.includes(' ') && other.replace(/\s+/g, '') === name) {
          hasSpaced = true;
          break;
        }
      }
      if (hasSpaced) continue;
    }
    result[name] = info;
  }
  return result;
}
