import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
const source=readFileSync(new URL('./background.js',import.meta.url),'utf8');
function harness(){const session={},local={},tabs=new Map([[1,{id:1,url:'https://46log.com/miguri'}],[2,{id:2,url:'https://saka46log.com/import'}],[3,{id:3,url:'https://saka46log.com/import'}]]),created=[];let listener;const store=obj=>({get:async key=>({[key]:obj[key]}),set:async data=>Object.assign(obj,structuredClone(data)),remove:async key=>{delete obj[key];}});const chrome={storage:{session:store(session),local:store(local)},alarms:{clear:async()=>{},get:async()=>null,create:async()=>{},onAlarm:{addListener(){}}},runtime:{onInstalled:{addListener(){}},onStartup:{addListener(){}},onMessage:{addListener(fn){listener=fn;}}},tabs:{create:async spec=>{const tab={...spec,id:50+created.length};created.push(tab);tabs.set(tab.id,tab);return tab;},get:async id=>tabs.get(id),update:async(id,spec)=>{Object.assign(tabs.get(id),spec);return tabs.get(id);},remove:async id=>tabs.delete(id),query:async()=>[],sendMessage:async()=>{},onRemoved:{addListener(){}}},action:{setBadgeText:async()=>{},setBadgeBackgroundColor:async()=>{},setTitle:async()=>{},onClicked:{addListener(){}}},windows:{update:async()=>{}}};vm.runInNewContext(source,{chrome,importScripts(){},URL,crypto:globalThis.crypto,Date,console,fetch:async()=>{throw new Error('Unexpected network write');}});const send=(message,id=2,url=tabs.get(id)?.url)=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Message timeout')),1000);listener(message,{url,frameId:0,tab:{id}},response=>{clearTimeout(timer);resolve(response);});});return {session,local,tabs,created,send};}
test('new target comes from sender, not untrusted page target; other origins rejected',async()=>{const h=harness();assert.equal((await h.send({type:'MIGURI46LOG_START',source:'fortunemusic',target:'46log'})).ok,true);assert.equal(h.session.miguriSyncJob.target,'saka46log');assert.equal(h.session.miguriSyncJob.auto,false);assert.equal((await h.send({type:'MIGURI46LOG_START',source:'fortunemusic'},3,'https://evil.invalid/import')).ok,false);});
test('pending new-site result is isolated by origin and initiating tab',async()=>{const h=harness();h.session.miguriSyncResult={target:'saka46log',returnTabId:2,completedAt:new Date().toISOString(),records:[{private:'fixture'}]};assert.equal((await h.send({type:'MIGURI46LOG_TAKE_RESULT'},1)).result,null);assert.equal((await h.send({type:'MIGURI46LOG_TAKE_RESULT'},3)).result,null);assert.equal((await h.send({type:'MIGURI46LOG_TAKE_RESULT'},2)).result.records.length,1);});
test('new source only returns Sakura lottery DTO, never writes old API',async()=>{const h=harness();await h.send({type:'MIGURI46LOG_START',source:'fortunemusic'});const job=h.session.miguriSyncJob;const response=await h.send({type:'MIGURI46LOG_RESULT',jobId:job.id,records:[{group:'nogizaka',sourceKey:'other'},{group:'sakurazaka',sourceKey:'s',member:'田村保乃',date:'2026-10-18',slot:1,applicationRound:'第1次',lotteryApplied:5,lotteryWon:0,lotteryReviewRequired:false,resultStatus:'lost',title:'Fixture',officialCookie:'MUST_NOT_COPY'}]},job.tabId);assert.equal(response.ok,true);const r=h.session.miguriSyncResult;assert.equal(r.version,2);assert.equal(r.records.length,1);assert.equal(r.records[0].won,0);assert.equal(r.records[0].officialCookie,undefined);assert.equal(r.autoContinue,false);assert.match(h.tabs.get(2).url,/^https:\/\/saka46log.com\/import/);});
test('new ACK neither chains Meets nor enables old auto-sync; only exact receipt acknowledged',async()=>{const h=harness(),completedAt=new Date().toISOString();h.session.miguriSyncResult={target:'saka46log',returnTabId:2,completedAt,autoContinue:true,next:'meets'};await h.send({type:'MIGURI46LOG_ACK_RESULT',completedAt:'wrong'});assert(h.session.miguriSyncResult);await h.send({type:'MIGURI46LOG_ACK_RESULT',completedAt});assert.equal(h.session.miguriSyncResult,undefined);assert.equal(h.created.length,0);assert.equal(h.local.miguriAutoSyncState,undefined);});
test('old Music-to-Meets continuation stays intact',async()=>{const h=harness(),completedAt=new Date().toISOString();h.session.miguriSyncResult={version:1,completedAt,autoContinue:true,next:'meets'};const r=await h.send({type:'MIGURI46LOG_ACK_RESULT',completedAt},1);assert.equal(r.continued,true);assert.equal(h.session.miguriSyncJob.source,'fortunemeets');assert.equal(h.session.miguriSyncJob.target,'46log');});
test('new site cannot start old automatic sync or Meets import',async()=>{const h=harness();for(const message of [{type:'MIGURI46LOG_RUN_AUTO'},{type:'MIGURI46LOG_SET_AUTO_ENABLED',enabled:true},{type:'MIGURI46LOG_START',source:'fortunemeets'}])assert.equal((await h.send(message)).ok,false);assert.equal(h.created.length,0);});
test('expired new receipt cannot be read',async()=>{const h=harness();h.session.miguriSyncResult={target:'saka46log',returnTabId:2,completedAt:new Date(Date.now()-3600000).toISOString()};assert.equal((await h.send({type:'MIGURI46LOG_TAKE_RESULT'})).result,null);});
